FROM node:22.12.0-alpine AS base

FROM base AS builder

WORKDIR /app

RUN corepack enable

RUN corepack prepare yarn@4.5.3 --activate

copy .yarn ./.yarn
COPY .yarnrc.yml ./
COPY package.json yarn.lock ./
COPY apps/website ./apps/website
COPY packages ./packages

RUN yarn workspaces focus @ph-blockchain/website

ENV NEXT_TELEMETRY_DISABLED 1

ARG SESSION_SECRET_KEY
ARG SERVER_USER_AGENT
ARG NEXT_PUBLIC_BASE_API_URL
ARG NEXT_PUBLIC_WS_API_URL
ARG SERVER_BASE_API_URL
ARG COOKIE_DOMAIN

ENV SESSION_SECRET_KEY=${SESSION_SECRET_KEY} \
    SERVER_USER_AGENT=${SERVER_USER_AGENT} \
    NEXT_PUBLIC_BASE_API_URL=${NEXT_PUBLIC_BASE_API_URL} \
    NEXT_PUBLIC_WS_API_URL=${NEXT_PUBLIC_WS_API_URL} \
    SERVER_BASE_API_URL=${SERVER_BASE_API_URL} \ 
    COOKIE_DOMAIN=${COOKIE_DOMAIN}

RUN yarn build:package

RUN yarn website build

FROM base AS runner
WORKDIR /app

ARG SESSION_SECRET_KEY
ARG SERVER_USER_AGENT
ARG NEXT_PUBLIC_BASE_API_URL
ARG NEXT_PUBLIC_WS_API_URL
ARG SERVER_BASE_API_URL
ARG COOKIE_DOMAIN

ENV NODE_ENV=production \
    SESSION_SECRET_KEY=${SESSION_SECRET_KEY} \
    SERVER_USER_AGENT=${SERVER_USER_AGENT} \
    NEXT_PUBLIC_BASE_API_URL=${NEXT_PUBLIC_BASE_API_URL} \
    NEXT_PUBLIC_WS_API_URL=${NEXT_PUBLIC_WS_API_URL} \
    SERVER_BASE_API_URL=${SERVER_BASE_API_URL}
    COOKIE_DOMAIN=${COOKIE_DOMAIN}

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001
USER nextjs

COPY --from=builder --chown=nextjs:nodejs /app/node_modules/tiny-secp256k1/lib/secp256k1.wasm ./node_modules/tiny-secp256k1/lib/
COPY --from=builder --chown=nextjs:nodejs /app/apps/website/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/apps/website/public ./apps/website/public
COPY --from=builder --chown=nextjs:nodejs /app/apps/website/.next/static ./apps/website/.next/static

CMD ["node", "apps/website/server.js"]